volumes:
  pgdata:

services:
  postgres:
    networks:
      local:
        aliases:
          - postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
     networks:
        - local
  
  networks:
    local: